# Generated by Django 4.1.6 on 2023-03-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
